config/routes.rb
Rails.application.routes.draw do
  resources :experts do
    collection do
      get '/success', action: "success"
    end
  end
  
  resources :consumers do
    collection do
      get '/success', action: "success"
      get '/questions', action: "questions"
    end
  end
  
  resources :consumer_answers, only: :index
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/consumer.rb
class Consumer < ApplicationRecord
  has_many :consumer_answers
  has_many :answers, through: :consumer_answers
end

app/models/consumer_answer.rb
class ConsumerAnswer < ApplicationRecord
  belongs_to :consumer
  belongs_to :answer
end

app/models/expert.rb
class Expert < ApplicationRecord
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers
  enum receiver: [:expert, :consumer]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/consumer_answers_controller.rb
class ConsumerAnswersController < ApplicationController
  def index
    @consumer_answers = ConsumerAnswer.all
  end
end

app/controllers/consumers_controller.rb
class ConsumersController < ApplicationController
  def edit
    @consumer = Consumer.find(params[:id])
  end

  def create
    @consumer = Consumer.create!
    
    params[:checkbox_ids].each do |answer_id|
      ConsumerAnswer.create(
        consumer_id: @consumer.id,
        answer_id: answer_id
      )
    end
    
    redirect_to edit_consumer_path(@consumer.id)
  end
  
  def update
    @consumer = Consumer.find(params[:id])
    @consumer.update(consumer_params)
    redirect_to success_consumers_path
  end
  
  def questions
    @questions = Question.where(receiver: 1)
  end
  
  def success
    
  end
  
  private
  
  def consumer_params
    params.require(:consumer).permit(:name, :email)
  end
end

app/controllers/experts_controller.rb
class ExpertsController < ApplicationController
  def new
    @expert = Expert.new
    @questions = Question.where(receiver: 0)
  end

  def create
    Expert.create(expert_params)
    redirect_to success_experts_path
  end
  
  def success
    
  end
  
  private
  
  def expert_params
    params.require(:expert).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/_answer.html.erb
<div class="col-sm-4">
  <input type="checkbox" name="checkbox_ids[]" value="<%= answer.id %>"><%= answer.text %>
</div>

app/views/consumer_answers/_consumer_answer.html.erb
<%= consumer_answer.consumer.name %> <br>
<%= consumer_answer.consumer.email %> <br>
<%= consumer_answer.answer.question.text %> <br>
<%= consumer_answer.answer.text %> <br> <br>

app/views/consumer_answers/index.html.erb
<%= render @consumer_answers %>

app/views/consumers/edit.html.erb
<div class="consumer container-fluid">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h1>Enter your name and email address to finish</h1>
      
      <%= form_for(@consumer) do |f| %>
        <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
        <%= f.text_field :email, class: "form-control", placeholder: "Email" %>
        
        <%= f.submit "Finish", class: "form-control btn btn-wide" %>
      <% end %>
    </div>
  </div>
</div>

app/views/consumers/questions.html.erb
<div class="consumer container-fluid">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <%= form_tag(consumers_path, method: :post) do %>
        <%= render @questions %>
        <%= submit_tag "Submit", class: "form-control btn btn-wide" %>
      <% end %>
    </div>
  </div>
</div>

app/views/consumers/success.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="text-center col-sm-8 col-sm-offset-2">
      <h1>Thanks for registering your interest!</h1>
      <h2>We're developing the website now so your feedback really helps. If you left an email address then we'll let you know when it's finished.</h2>
    </div>
  </div>
</div>

app/views/experts/new.html.erb
<div class="expert container-fluid">
  <div class="row">
    <div class="banner col-sm-12">
      <h2 class="text-center">Banner</h2>
    </div>
    
    <div class="col-sm-6 col-sm-offset-3">
      <h1 class="text-center">Register</h1>
      <%= form_for(@expert) do |f| %>
        <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
        <%= f.text_field :email, class: "form-control", placeholder: "Email" %>

        <%= render @questions %>

        <%= f.submit "Join the Community", class: "form-control btn btn-wide" %>
      <% end %>
    </div>
  </div>
</div>

app/views/experts/success.html.erb
<h1>success</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MindfieldSmoketest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/_question.html.erb
<div class="clearfix"></div>

<div class="mb-30">
  <h2><%= question.text %></h2>

  <%= render question.answers %>
  
  <div class="clearfix"></div>
</div>